typography_spectrum: 0.9515546741895378
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8216254352591932
  lightness: 0.8144698988180608
  saturation: 0.009866912150755525
  rhythmicContrast: 0.34731451026163995
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.92396
analytics:
  google: null
  facebook: null
  twitter: null
name: bhwebtech
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: c099f30e-ec09-4a37-a611-56c4dbb6e0ce
    type: content
favicon: null
description: Bringing Web Tech & Entrepreneurs together
purpose: []
